
// TODO: Handle Multiple University

export const allowedEmailDomains = [
  "stonybrook.edu",
]

export enum UniversityCode {
  STONY_BROOK = "SBU"
}

export const DEFAULT_PAGE_LENGTH = {
  EVENT: 8,
  COMMUNITY: 8,
  STORE: 8,
  NOTIFICATION: 10,
  USER_ACTIVITY: 10,
}

export const REVALIDATE_TIME = {
  EVENT: 60,
  COMMUNITY: 60,
  STORE: 60,
}


// TODO: Handle Multiple Universities' Major
export const MajorList = ["NONE", "UNDECLARED", "AAS","ACC","ADV","AFH","AFS","AIM","AMR","AMS","ANP","ANT","ARB","ARH","ARS","ASC","AST","ATM","BCP", "BCH", "BIO","BME","BUS","CAR","CCS","CDS","CEF","CHE","CHI","CIV","CLL","CLS","CLT","CME","COM","CSE","CWL","DAN","DIA","EAS","EBH","ECO","EDP","EEL","EEO","EGL","ENS","ENV","ESE","ESG","ESM","EST","EUR","EXT","FLA","FLM","FRN","GEO","GER","GLI","GRK","GSS","HAD","HAL","HAN","HAT","HBA","HBH","HBM","HBP","HBW","HBY","HDG","HDO","HDP","HIN","HIS","HNI","HON","HUE","HUF","HUG","HUI","HUL","HUR","HUS","HWC","IAE","IAP","INT","ISE","ITL","JDH","JDS","JPN","JRN","KOR","KSW","LAC","LAN","LAT","LCR","LDR","LHD","LHW","LIA","LIN","MAE","MAP","MAR","MAT","MDA","MEC","MSL","MUS","MVL","OAE","PER","PHI","PHY","POL","POR","PSY","RLS","RUS","SBU","SCH","SCI","SKT","SLN","SOC","SPN","SSE","SUS","THR","TRK","TVW","UKR","VIP","WAE","WRT","WSE","WST"]


export enum MajorType {
  NONE = "NONE",
  UNDECLARED = "UNDECLARED",
  AAS = "AAS",
  ACC = "ACC",
  ADV = "ADV",
  AFH = "AFH",
  AFS = "AFS",
  AIM = "AIM",
  AMR = "AMR",
  AMS = "AMS",
  ANP = "ANP",
  ANT = "ANT",
  ARB = "ARB",
  ARH = "ARH",
  ARS = "ARS",
  ASC = "ASC",
  AST = "AST",
  ATM = "ATM",
  BCP = "BCP",
  BCH = "BCH",
  BIO = "BIO",
  BME = "BME",
  BUS = "BUS",
  CAR = "CAR",
  CCS = "CCS",
  CDS = "CDS",
  CEF = "CEF",
  CHE = "CHE",
  CHI = "CHI",
  CIV = "CIV",
  CLL = "CLL",
  CLS = "CLS",
  CLT = "CLT",
  CME = "CME",
  COM = "COM",
  CSE = "CSE",
  CWL = "CWL",
  DAN = "DAN",
  DIA = "DIA",
  EAS = "EAS",
  EBH = "EBH",
  ECO = "ECO",
  EDP = "EDP",
  EEL = "EEL",
  EEO = "EEO",
  EGL = "EGL",
  ENS = "ENS",
  ENV = "ENV",
  ESE = "ESE",
  ESG = "ESG",
  ESM = "ESM",
  EST = "EST",
  EUR = "EUR",
  EXT = "EXT",
  FLA = "FLA",
  FLM = "FLM",
  FRN = "FRN",
  GEO = "GEO",
  GER = "GER",
  GLI = "GLI",
  GRK = "GRK",
  GSS = "GSS",
  HAD = "HAD",
  HAL = "HAL",
  HAN = "HAN",
  HAT = "HAT",
  HBA = "HBA",
  HBH = "HBH",
  HBM = "HBM",
  HBP = "HBP",
  HBW = "HBW",
  HBY = "HBY",
  HDG = "HDG",
  HDO = "HDO",
  HDP = "HDP",
  HIN = "HIN",
  HIS = "HIS",
  HNI = "HNI",
  HON = "HON",
  HUE = "HUE",
  HUF = "HUF",
  HUG = "HUG",
  HUI = "HUI",
  HUL = "HUL",
  HUR = "HUR",
  HUS = "HUS",
  HWC = "HWC",
  IAE = "IAE",
  IAP = "IAP",
  INT = "INT",
  ISE = "ISE",
  ITL = "ITL",
  JDH = "JDH",
  JDS = "JDS",
  JPN = "JPN",
  JRN = "JRN",
  KOR = "KOR",
  KSW = "KSW",
  LAC = "LAC",
  LAN = "LAN",
  LAT = "LAT",
  LCR = "LCR",
  LDR = "LDR",
  LHD = "LHD",
  LHW = "LHW",
  LIA = "LIA",
  LIN = "LIN",
  MAE = "MAE",
  MAP = "MAP",
  MAR = "MAR",
  MAT = "MAT",
  MDA = "MDA",
  MEC = "MEC",
  MSL = "MSL",
  MUS = "MUS",
  MVL = "MVL",
  OAE = "OAE",
  PER = "PER",
  PHI = "PHI",
  PHY = "PHY",
  POL = "POL",
  POR = "POR",
  PSY = "PSY",
  RLS = "RLS",
  RUS = "RUS",
  SBU = "SBU",
  SCH = "SCH",
  SCI = "SCI",
  SKT = "SKT",
  SLN = "SLN",
  SOC = "SOC",
  SPN = "SPN",
  SSE = "SSE",
  SUS = "SUS",
  THR = "THR",
  TRK = "TRK",
  TVW = "TVW",
  UKR = "UKR",
  VIP = "VIP",
  WAE = "WAE",
  WRT = "WRT",
  WSE = "WSE",
  WST = "WST",
}


